### ISSUE TITLE
[question] How to troubleshoot cluster issues?

### ISSUE THREAD

**Issue by ludwig-reekoh** [moscajs/aedes-cli#155]
I have two instances of Aedes-cli running, and there is a load balancer in front of them.

It uses Redis a Redis master/slave/slave cluster as as an emitter and for persistence.

I see that Redis contains only one key, 'retained'.

The scenario:
1. A subscriber connects to aedes via the load balancer, and listens on testtopic
2. A publisher  connects to aedes via the load balancer, and publishes on testtopic. The subscriber receives the message.
3. I disconnect the publisher, then have it reconnect via the load balancer. It publishes on testtopic. The subscriber receives no message.

How do I troubleshoot this or isolate where the issue is?

**Comment by robertsLando** [comment]
are you using mqemitter redis?
