### ISSUE TITLE
[bug] authorization does not block retained messages from unauthorised paths

### ISSUE THREAD

**Issue by wardv** [moscajs/aedes-cli#158]
**System Information**
- Aedes: 0.46.1
- NodeJS: 16.18.1
- OS: Debian 11
- Arch: amd64

**Describe the bug**
I manage to publish and subscribe to a topic that is not in the authorised paths for the user.

**To Reproduce**
1. use following conf file:
`module.exports = {
  protos: ['tcp'],
  host: '127.0.0.1',
  port: 1883,
  wsPort: 3000,
  wssPort: 4000,
  tlsPort: 8883,
  brokerId: 'aedes-cli',
  credentials: './credentials.json',
  persistence: {
    name: 'mongodb',
    options: {
      url: 'mongodb://127.0.0.1/aedes'
    }
  },
  mq: {
    name: 'mongodb',
    options: {
      url: 'mongodb://127.0.0.1/aedes'
    }
  },
  key: null,
  cert: null,
  rejectUnauthorized: true,
  verbose: false,
  veryVerbose: false,
  noPretty: false
}
`

2. create two users:
`./aedes adduser ward pwd4ward --credentials ./credentials.json --authorize-publish 'ward/**' --authorize-subscribe 'ward/**'`
`./aedes adduser pete pwd4pete --credentials ./credentials.json --authorize-publish 'pete/**' --authorize-subscribe 'pete/**'`

3. publish retained message using first user
`mosquitto_pub -h 34.69.176.86 -u ward -P pwd4ward -t 'ward/1' -m mymessage -r`

4. subscribe to everything with other user
`mosquitto_sub -h 34.69.176.86 -u pete -P pwd4pete -t '#'`
results in: `mymessage`

**Expected behavior**
I would expect the broker to log an error saying "subscription not authorized".  
Even if no error is logged, the message "mymessage" from user ward should not be shown to user pete

**Comment by robertsLando** [comment]
Actually the logic is not correct: https://github.com/moscajs/aedes-cli/blob/master/lib/authorizer.js#L62

Would you mind submitting a PR with a fix?

**Comment by wardv** [comment]
see pull request #159

**Comment by wardv** [comment]
this was fixed some time ago in Aedes: [https://github.com/moscajs/aedes/pull/720](https://github.com/moscajs/aedes/pull/720)

**Comment by wardv** [comment]
yep, sorry.  Created a server in the cloud with Aedes a year ago and finally came around to using it... should have upgraded first. My bad!
