### ISSUE TITLE
[bug] a user can publish in any topic even if you set a limitation in credentials.json

### ISSUE THREAD

**Issue by iwillflytothemoon** [moscajs/aedes-cli#30]
**System Information**
Aedes-cli: 0.3.0
NodeJS: 14.5.0
OS: Alpine 3.11.6
Arch: x86_64

**Describe the bug**
A user can publish in any topic even if you set a limitation in authorizePublish under credentials.json

**To Reproduce**
1. Run the latest aedes-cli server
2. Create 2 or 3 users and add access limit in topic for each user. 
3. Subscribe to user1 topic
4. Publish a topic to user1 topic using user2 or user3

**Expected behavior**
A user should be limited to what topic a user can access to based on authorizePublish setting under credentials.json

**Additional context**
![image](https://user-images.githubusercontent.com/6613339/87923621-5c4fa600-cab0-11ea-9ad9-d8de649af2bf.png)

**Comment by robertsLando** [comment]
@iwillflytothemoon Sorry, another thing that has changed from mosca to aedes, try the branch with the fix linked here

**Comment by robertsLando** [comment]
@iwillflytothemoon Is it working?

**Comment by iwillflytothemoon** [comment]
@robertsLando all good now, it is working. Thanks!
