### ISSUE TITLE
[question] How does persistence works in Aedes?

### ISSUE THREAD

**Issue by iwillflytothemoon** [moscajs/aedes-cli#85]
If I publish a message with QoS of >1 without any subscriber at first, will it store the messages in the broker?
And after publishing the message, then I subscribed in the same topic, will I get all the messages published?

**Comment by robertsLando** [comment]
Persistence stores all `incoming` `outgoing` qos > 0 messages, `subscriptions`  and `retained` messages. In your case you maybe want to use `retained` messages, when a retained message is sent to broker to a specific topic the broker will store it in persistence and send it back to clients when they subscribe to a topic (or a wildecard) that matches that retained message topic (and any others matches)

**Comment by iwillflytothemoon** [comment]
I checked retained messages and it's only store 1 message at a time right?

**Comment by robertsLando** [comment]
@iwillflytothemoon One for each topic, yes. If you need an historical storage checkout influxdb (timeseries database) telegraf (with mqtt integration to store mqtt messages) and also grafana (for visualization)
